// Auto-generated by scripts/import-from-SDK.mjs
// Phase 1.5 additions appended below — do not remove
export { cn } from './utils/cn'

// ── Phase 1.5 — new OTF primitives ──────────────────────────────
// layout
export * from './layout'

// nav
export * from './nav'

// feedback (toast emitter + Toaster)
export * from './feedback'

// text (GradientHeading, AnimatedNumber, TextReveal, Typewriter)
export * from './text'

// backgrounds (GradientBackground, AnimatedGradient, DottedBackground, NoiseBackground)
export * from './backgrounds'

// headers (ScrollHeader)
export * from './headers'

// motion (FadeIn, SlideIn, ScaleIn, Reveal, Stagger, Morph, Ripple, Parallax, Transition)
export * from './motion'

// data (DataGrid, Filters, ActionBar, SortableList)
export * from './data'

// app-shell (AppShell, Sidebar compound, WorkspacesMenu, UserMenu, SidebarResizer, BillingStatus, SortableNav)
export * from './app-shell'
// ────────────────────────────────────────────────────────────────

// primitives (Radix-based — from SDK import, curated)
export * from './primitives/Accordion'
export * from './primitives/Alert'
export * from './primitives/AlertDialog'
export * from './primitives/AspectRatio'
export * from './primitives/Avatar'
export * from './primitives/Badge'
export * from './primitives/Button'
export * from './primitives/Calendar'
export * from './primitives/Card'
export * from './primitives/Carousel'
export * from './primitives/Chart'
export * from './primitives/Checkbox'
export * from './primitives/Collapsible'
// export * from './primitives/Command'     // collides with nav/CommandPalette (CommandGroup, CommandItem)
export * from './primitives/ContextMenu'
export * from './primitives/Dialog'
export * from './primitives/Drawer'
export * from './primitives/DropdownMenu'
export * from './primitives/Form'
export * from './primitives/HoverCard'
export * from './primitives/Input'
export * from './primitives/InputOtp'
export * from './primitives/Label'
export * from './primitives/Menubar'
export * from './primitives/NavigationMenu'
export * from './primitives/Pagination'
export * from './primitives/Popover'
export * from './primitives/Progress'
export * from './primitives/Radio'
export * from './primitives/Resizable'
export * from './primitives/ScrollArea'
export * from './primitives/Select'
export * from './primitives/Separator'
export * from './primitives/Sheet'
export * from './primitives/Skeleton'
export * from './primitives/Slider'
// export * from './primitives/Sonner'      // collides with feedback/Toaster
export * from './primitives/Spinner'
export * from './primitives/Switch'
export * from './primitives/Table'
export * from './primitives/Tabs'
export * from './primitives/Textarea'
export * from './primitives/Toggle'
export * from './primitives/ToggleGroup'
export * from './primitives/Tooltip'

// ── components ───────────────────────────────────────────────────
export * from './components/EmptyState'

// ── SDK stubs ──────────────────────────────────────────────
// Commented out in Phase 1.5: these have broken relative imports
// (../primitives/button, ../utils/cn etc) because the SDK
// import script placed them at the wrong directory depth.
// They will be properly ported on-demand in Phase 3.
//
// components: Banner, Breadcrumb, DataTable, Hotkeys, IconBadge,
//   LoadingOverlay, Persona, PropertyList, Stat, Stepper,
//   StructuredList, Timeline, CommandItem, DataGrid, EmptyState, Toaster
// blocks: ChatDetail, FeedbackModal, FileCards, FilesList,
//   IntegrationCard, InviteModal, ManageTagsModal, MessagesCard,
//   MetricCard, NotificationSettings, OrganizationMenu, RolesMenu,
//   SelectUsersModal, SidebarLayout*, StackedLayout*, TaskCard,
//   UserMenu, WorkspaceMembers, SortableTaskList
// advanced: BulkActions, CommandBar, Filters, Kanban, ToggleButton
// charts: AreaChart, BarChart, LineChart, Sparkline
// engagement: Beacon, Tour
// forms: ArrayField, AutoForm, DatePicker, Field, FileUpload,
//   Form, ObjectField, PasswordInput, SearchInput, StepForm
// layouts: AppShell, Container, Navbar, Page, ResizeBox,
//   Sidebar, SplitPage, Stack
