export * from './presets'
export * from './FadeIn'
export * from './SlideIn'
export * from './ScaleIn'
export * from './Reveal'
export * from './Stagger'
export * from './Morph'
export * from './Ripple'
export * from './Parallax'
export * from './useLayoutId'
export * from './Transition'
// re-export useful motion primitives
export { motion, AnimatePresence, useInView, useMotionValue, useSpring, useTransform, useScroll, type Variants } from 'motion/react'
